name: Delete Repository

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository to delete:'
        required: true

jobs:
  delete-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Repository
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repo = "${{ github.event.inputs.repo }}";
            const endpoint = `DELETE /repos/Deon-J-Butler/${repo}`;
            await github.rest.request(endpoint);
